cmd: "python"
name: "PQS: test add"
args:
  - "-m"
  - "test"
  - "add"
sh: true,
targets:
  "PQS: test edit-transient":
      cmd: "python"
      args:
        - "-m"
        - "test"
        - "edit-transient"
  "PQS: test edit-pending":
      cmd: "python"
      args:
        - "-m"
        - "test"
        - "edit-pending"
  "PQS: test edit-persistent":
      cmd: "python"
      args:
        - "-m"
        - "test"
        - "edit-persistent"
  "PQS: test edit-persistent-wrong":
      cmd: "python"
      args:
        - "-m"
        - "test"
        - "edit-persistent-wrong"
  "Conda: check environment":
      cmd: "conda"
      args:
        - "info"
        - "--envs"
