# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect_form.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConnectForm(object):
    def setupUi(self, ConnectForm):
        ConnectForm.setObjectName("ConnectForm")
        ConnectForm.resize(306, 226)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ConnectForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(ConnectForm)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.connectorLabel = QtWidgets.QLabel(ConnectForm)
        self.connectorLabel.setObjectName("connectorLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.connectorLabel)
        self.connectorComboBox = QtWidgets.QComboBox(ConnectForm)
        self.connectorComboBox.setObjectName("connectorComboBox")
        self.connectorComboBox.addItem("")
        self.connectorComboBox.addItem("")
        self.connectorComboBox.addItem("")
        self.connectorComboBox.addItem("")
        self.connectorComboBox.addItem("")
        self.connectorComboBox.addItem("")
        self.connectorComboBox.addItem("")
        self.connectorComboBox.addItem("")
        self.connectorComboBox.addItem("")
        self.connectorComboBox.addItem("")
        self.connectorComboBox.addItem("")
        self.connectorComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.connectorComboBox)
        self.usernameLabel = QtWidgets.QLabel(ConnectForm)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(ConnectForm)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(ConnectForm)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(ConnectForm)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.hostLabel = QtWidgets.QLabel(ConnectForm)
        self.hostLabel.setObjectName("hostLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.hostLabel)
        self.hostLineEdit = QtWidgets.QLineEdit(ConnectForm)
        self.hostLineEdit.setObjectName("hostLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hostLineEdit)
        self.portLabel = QtWidgets.QLabel(ConnectForm)
        self.portLabel.setObjectName("portLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.portSpinBox = QtWidgets.QSpinBox(ConnectForm)
        self.portSpinBox.setMaximum(65535)
        self.portSpinBox.setObjectName("portSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.portSpinBox)
        self.databaseLabel = QtWidgets.QLabel(ConnectForm)
        self.databaseLabel.setObjectName("databaseLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.databaseLabel)
        self.databaseLineEdit = QtWidgets.QLineEdit(ConnectForm)
        self.databaseLineEdit.setObjectName("databaseLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.databaseLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.connectButton = QtWidgets.QPushButton(ConnectForm)
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout.addWidget(self.connectButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ConnectForm)
        QtCore.QMetaObject.connectSlotsByName(ConnectForm)

    def retranslateUi(self, ConnectForm):
        _translate = QtCore.QCoreApplication.translate
        ConnectForm.setWindowTitle(_translate("ConnectForm", "Connect Form"))
        self.titleLabel.setText(_translate("ConnectForm", "Connect to engine"))
        self.connectorLabel.setText(_translate("ConnectForm", "connector"))
        self.connectorComboBox.setItemText(0, _translate("ConnectForm", "postgresql"))
        self.connectorComboBox.setItemText(1, _translate("ConnectForm", "postgresql+psycopg2"))
        self.connectorComboBox.setItemText(2, _translate("ConnectForm", "postgresql+pg8000"))
        self.connectorComboBox.setItemText(3, _translate("ConnectForm", "mysql"))
        self.connectorComboBox.setItemText(4, _translate("ConnectForm", "mysql+mysqldb"))
        self.connectorComboBox.setItemText(5, _translate("ConnectForm", "mysql+mysqlconnector"))
        self.connectorComboBox.setItemText(6, _translate("ConnectForm", "mysql+oursql"))
        self.connectorComboBox.setItemText(7, _translate("ConnectForm", "oracle"))
        self.connectorComboBox.setItemText(8, _translate("ConnectForm", "oracle+cx_oracle"))
        self.connectorComboBox.setItemText(9, _translate("ConnectForm", "mssql+pyodbc"))
        self.connectorComboBox.setItemText(10, _translate("ConnectForm", "mssql+pymssql"))
        self.connectorComboBox.setItemText(11, _translate("ConnectForm", "sqlite"))
        self.usernameLabel.setText(_translate("ConnectForm", "username"))
        self.passwordLabel.setText(_translate("ConnectForm", "password"))
        self.hostLabel.setText(_translate("ConnectForm", "host"))
        self.portLabel.setText(_translate("ConnectForm", "port"))
        self.databaseLabel.setText(_translate("ConnectForm", "database"))
        self.connectButton.setText(_translate("ConnectForm", "Connect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConnectForm = QtWidgets.QWidget()
    ui = Ui_ConnectForm()
    ui.setupUi(ConnectForm)
    ConnectForm.show()
    sys.exit(app.exec_())

